### ISSUE TITLE
Memory leak if shutil.rmtree keeps failing

### ISSUE THREAD

**Issue by guojiex** [FederatedAI/eggroll#556]
Please review the pull request https://github.com/WeBankFinTech/eggroll/pull/551

We are seeing some error like:

==== detail start, at 20211220.032154.893 ====
Traceback (most recent call last):
File "/data/projects/fate/eggroll/python/eggroll/core/utils.py", line 146, in wrapper
return func(*args, **kw)
File "/data/projects/fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 247, in run_task
shutil.rmtree(path)
File "/opt/app-root/lib64/python3.6/shutil.py", line 486, in rmtree
_rmtree_safe_fd(fd, path, onerror)
File "/opt/app-root/lib64/python3.6/shutil.py", line 424, in _rmtree_safe_fd
_rmtree_safe_fd(dirfd, fullname, onerror)
File "/opt/app-root/lib64/python3.6/shutil.py", line 428, in _rmtree_safe_fd
onerror(os.rmdir, fullname, sys.exc_info())
File "/opt/app-root/lib64/python3.6/shutil.py", line 426, in _rmtree_safe_fd
os.rmdir(name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: '0'

The path to be deleted is :
/data/projects/fate/eggroll/data/IN_MEMORY/2021122020272213924715_sir_0_0_guest_20001

this lead to memory leak of our container, since each clean job cannot finish in eggpair, and those process just keep retrying.
So I just catch the OSError and log it, but don't fail on error.

**Comment by guojiex** [comment]
friendly ping?

**Comment by guojiex** [comment]
ping?

**Comment by guojiex** [comment]
ping
