### ISSUE TITLE
Traceback (most recent call last):  KeyError: 'eggs'

### ISSUE THREAD

**Issue by mgyboom** [FederatedAI/eggroll#565]
python -m unittest test_roll_pair.TestRollPairStandalone

[ERROR][2022-01-27 20:13:25,194][eggpair-command-server_1,pid:44650,tid:139621291792128][command_router.py:93.dispatch] - Failed to dispatch to [v1/egg-pair/runTask], task_name: withStores, request: [<ErTask(id=er_session_py_20220127.201304.596_10.58.14.24-py-job-20220127.201325.184981_withStores-task-0, name=withStores, inputs=[<ErPartition(id=0, store_locator=<ErStoreLocator(id=0, store_type=ROLL_PAIR_CACHE, namespace=er_session_meta, name=er_session_py_20220127.201304.596_10.58.14.24, path=, total_partitions=4, partitioner=BYTESTRING_HASH, serdes=PICKLE) at 0x7f02b41baac8>, processor=<ErProcessor(id=17, server_node_id=2, name=, processor_type=egg_pair, status=RUNNING, command_endpoint=<ErEndpoint(host=10.58.14.24, port=7987) at 0x7f02b41ba630>, transfer_endpoint=<ErEndpoint(host=10.58.14.24, port=27529) at 0x7f02b41bae48>, pid=44650, options=[{}], tag=) at 0x7f02b41ba7f0>, rank_in_node=0) at 0x7f02b41ba128>], outputs=[], job=<ErJob(id=er_session_py_20220127.201304.596_10.58.14.24-py-job-20220127.201325.184981_withStores, name=withStores, inputs=[<ErStore(store_locator=<ErStoreLocator(id=0, store_type=ROLL_PAIR_CACHE, namespace=er_session_meta, name=er_session_py_20220127.201304.596_10.58.14.24, path=, total_partitions=4, partitioner=BYTESTRING_HASH, serdes=PICKLE) at 0x7f02b41ba5f8>, partitions=[***, len=4], options=[{'eggroll.session.id': 'er_session_py_20220127.201304.596_10.58.14.24', 'eggroll.resourcemanager.clustermanager.port': '12017', 'total_partitions': '4', 'eggroll.session.deploy.mode': 'standalone', 'store_type': 'ROLL_PAIR_CACHE', 'create_if_missing': 'True'}]) at 0x7f02b41ba898>], outputs=[], functors=[1], options={}) at 0x7f02b41ba438>) at 0x7f02b41badd8>]
Traceback (most recent call last):
  File "/data/projects/fate/eggroll/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 658, in run_task
    value=self.functor_serdes.serialize(f(task)))
  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs
    eggs = input_adapter.get('eggs')
  File "/data/projects/fate/eggroll/python/eggroll/core/pair_store/adapter.py", line 190, in get
    return self.data[key]
KeyError: 'eggs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/projects/fate/eggroll/python/eggroll/core/command/command_router.py", line 91, in dispatch
    call_result = _method(_instance, *deserialized_args)
  File "/data/projects/fate/eggroll/python/eggroll/core/utils.py", line 194, in wrapper
    raise RuntimeError(msg)
RuntimeError: 

==== detail start, at 20220127.201325.192 ====
Traceback (most recent call last):
  File "/data/projects/fate/eggroll/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 658, in run_task
    value=self.functor_serdes.serialize(f(task)))
  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs
    eggs = input_adapter.get('eggs')
  File "/data/projects/fate/eggroll/python/eggroll/core/pair_store/adapter.py", line 190, in get
    return self.data[key]
KeyError: 'eggs'

==== detail end ====

**Comment by luzengxiangcn** [comment]
same issue

**Comment by huxinxue** [comment]
I encountered the same problem. Have you found a solution?

**Comment by mgyboom** [comment]
> I encountered the same problem. Have you found a solution?

Sorry, I haven't found a solution to deal with it.

**Comment by luzengxiangcn** [comment]
tag : v2.4.4 works well for me

> I encountered the same problem. Have you found a solution?
